name: Deploy Backend Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build --no-cache \
            --build-arg PORT=${{ vars.PORT }} \
            --build-arg DATABASE_NAME=${{ vars.DATABASE_NAME }} \
            --build-arg ALLOW_ORIGIN=${{ vars.ALLOW_ORIGIN }} \
            --build-arg DATABASE_USERNAME=${{ vars.DATABASE_USERNAME }} \
            --build-arg DATABASE_PASSWORD=${{ vars.DATABASE_PASSWORD }} \
            --build-arg HOST=${{ vars.HOST }} \
            --build-arg DB_PORT=${{ vars.DB_PORT }} \
            -t hub.mydevpartner.website/backend .

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: hub.mydevpartner.website
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish Image to Docker Registry
        run: docker push hub.mydevpartner.website/backend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: hub.mydevpartner.website
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Image from Docker Registry
        run: docker pull hub.mydevpartner.website/backend:latest

      - name: Create Docker Network
        run: docker network create pg_network || true

      - name: Delete Old Containers
        run: |
          docker rm -f backend-container || true
          docker rm -f postgres-container || true
          docker rm -f pgadmin-container || true

      - name: Run PostgreSQL Container
        run: |
          docker run -d --name postgres-container \
          --network pg_network \
          -e POSTGRES_DB=${{ vars.DATABASE_NAME }} \
          -e POSTGRES_USER=${{ vars.DATABASE_USERNAME }} \
          -e POSTGRES_PASSWORD=${{ vars.DATABASE_PASSWORD }} \
          -v pgdata:/var/lib/postgresql/data \
          postgres:latest

      - name: Run pgAdmin Container
        run: |
          docker run -d --name pgadmin-container \
          --network pg_network \
          -e PGADMIN_DEFAULT_EMAIL=${{ secrets.PGADMIN_EMAIL }} \
          -e PGADMIN_DEFAULT_PASSWORD=${{ secrets.PGADMIN_PASSWORD }} \
          -p 8000:80 \
          dpage/pgadmin4

      - name: Run Backend Container
        run: |
          docker run -d -p ${{ vars.PORT }}:${{ vars.PORT }} --name backend-container \
          --network pg_network \
          -e DATABASE_NAME=${{ vars.DATABASE_NAME }} \
          -e ALLOW_ORIGIN=${{ vars.ALLOW_ORIGIN }} \
          -e DATABASE_USERNAME=${{ vars.DATABASE_USERNAME }} \
          -e DATABASE_PASSWORD=${{ vars.DATABASE_PASSWORD }} \
          -e HOST=postgres-container \
          -e DB_PORT=${{ vars.DB_PORT }} \
          hub.mydevpartner.website/backend:latest
