ame: Deploy nextjs application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Build docker image
        run: |
          docker build --no-cache \
            --build-arg NEXT_PUBLIC_API_URL=${{ vars.NEXT_PUBLIC_API_URL }} \
            -t hub.custom.website/nextjs-frontend .

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: hub.custom.website
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish image to Docker Registry
        run: docker push hub.custom.website/nextjs-frontend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: hub.custom.website
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull image from Docker Registry
        run: docker pull hub.custom.website/nextjs-frontend:latest

      - name: Delete old container
        run: docker rm -f nextjs-frontend-container || true

      - name: Run docker container
        run: |
          docker run -d -p 3000:3000 --name nextjs-frontend-container \
          -e NEXT_PUBLIC_API_URL=${{ vars.NEXT_PUBLIC_API_URL }} \
          hub.custom.website/nextjs-frontend:latest
